### ISSUE TITLE
1.Spezialisierung des Themas

### ISSUE THREAD

**Issue by gr2Natasa** [tuwien-geoweb/g02-2014#6]
Spezialisierung auf eine bestimmte Nutzergruppe (z.B.: Hundebesitzer, Familien,..)

**Comment by laganna** [comment]
- Zoomen auf aktuellen Standort
- Wohnstandortanalyse speziell für keine Autobesitzer - Einbindung des öffentlichen Verkehrs, Radfahranlagen, Carsharing,...
- Einwohnerzahlen, demographische Verteilung auf Bezirksebene darstellen

**Comment by ahocevar** [comment]
Projektplan ist schlüssig, eventuell noch ein bisschen etwas über das User Interface hinzufügen (und wenn's nur ein Hinweis ist, dass es so aussehen soll wie die censusmap-Demo).

Ihr könnt mit der Umsetzung beginnen.

**Comment by laganna** [comment]
user interface:
-karte mit drop-down menü (demographische Kennzahlen wie z.B.: Altersgruppen, Geschlecht, Einwohnerdichte,..)
- Ankreuzkästchen mit den verschiedenen Einrichtungen (z.B.: Radfahranlagen, ÖV-Infrastruktur, Hundezonen,..)
